---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: enforcer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cm-reader-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - 'get'
  - 'list'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cm-reader-clusterrolebinding
roleRef:
  kind: ClusterRole
  name: cm-reader-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: enforcer
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: naas
  namespace: default
  name: enforcer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enforcer
  template:
    metadata:
      labels:
        app: enforcer
      name: enforcer
    spec:
      serviceAccountName: enforcer
      initContainers:
      - name: inventory
        image: networkop/naas
        env:
        - name: INVENTORY
          value: "LS0tCmRldmljZWE6CiAgaG9zdG5hbWU6IDE3Mi4xNy4wLjEKICBwb3J0OiA5MDAwCiAgdXNlcm5hbWU6IGFkbWluCiAgcGFzc3dvcmQ6IGFkbWluCiAgcGxhdGZvcm06IGVvcwpkZXZpY2ViOgogIGhvc3RuYW1lOiAxNzIuMTcuMC4xCiAgcG9ydDogOTAwMQogIHVzZXJuYW1lOiBhZG1pbgogIHBhc3N3b3JkOiBhZG1pbgogIHBsYXRmb3JtOiBlb3M="
        command: [/app/enforcer_init.py]
        volumeMounts:
        - name: init-script
          mountPath: /app
          readOnly: true
        - name: inventory
          mountPath: /etc/nornir
      containers:
        - name: enforcer
          image: networkop/naas
          ports:
            - containerPort: 80
          command: [/app/enforcer.py]
          volumeMounts:
            - name: main-script
              mountPath: /app
              readOnly: true
            - name: inventory
              mountPath: /etc/nornir
      volumes:
        - name: main-script
          configMap:
            name: enforcer-cm
            defaultMode: 0755
            items:
              - key: script
                path: enforcer.py
        - name: init-script
          configMap:
            name: enforcer-init-cm
            defaultMode: 0755
            items:
              - key: script
                path: enforcer_init.py
        - name: inventory
          emptyDir: {}