---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: compliance-check-scheduler
spec:
  jobTemplate:
    metadata:
      name: compliance-checker
    spec:
      template:
        metadata:
        spec:
          containers:
          - name: compliance-checker
            image: networkop/naas
            command:
              - wget 
              - -q 
              - "--post-data='{\"devices\": [\"all\"] }' "
              - --header='Content-Type:application/json' 
              - http://schedule/configure
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
