---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-a
  labels:
    mutate: "true"
    validate: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-b
  labels:
    mutate: "true"
    validate: "true"