---
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: validating-webhook
webhooks:
  - name: opa.validating.webhook
    namespaceSelector:
      matchLabels:
        validate: "true"
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["network.as.a.service"]
        apiVersions: ["*"]
        resources: ["interfaces"]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZtZ0F3SUJBZ0lVTWRxNTlQWkM5RjNmTThPWkRKQURTa2xNenBRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01ZV1J0YVhOemFXOXVYMk5oTUNBWERURTVNVEF3TVRFMU1USTFORm9ZRHpJeQpPVE13TnpFMk1UVXhNalUwV2pBWE1SVXdFd1lEVlFRRERBeGhaRzFwYzNOcGIyNWZZMkV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURPQUFNM0RmdFBVMDU1U09kOHViZ2ZxKzg3VTFyMC9EdEgKOHVuS1p0L1BrK1BwZ2s3Z09lczBxNElBbVNsemFFNWN5bXhFYlo3SW92ZzU0QWtQWFBFVENDek5ITFRINUJHRwpJTEViOS9YYlZLUm56Wk40Zk9PekNnZEpVcEdhTjBlcWNFdTIxby9nVkl3TmdRMWRBa0ZzdmpFTkZnd0o5M1FQClQ4N0pqeE14VCtYNGVpYmx6emdUeU9oWnVmTEV6a1dKVis0RngyZFFvZzdFTGlINlN0YlZVOSt1TUFPRHZrRTAKd0dUUUZ6cm9Iem96aXhScVoyWDZ1TENrc2lTNG1tZlhKQUZqSmRYZHQ1ekZKZzVlZzlLdm1weEErU0RwbTI3TApySUtoTUQwazJJRmFuYjQzeXpDcVV3anhjOTZBT01jSDByNzhLQkN1dXpMVjBLbWJJeUZ0QWdNQkFBR2pVekJSCk1CMEdBMVVkRGdRV0JCVFZjMFgvMDZOSDE1TW9TNUd1TzVDN3FJQUZjREFmQmdOVkhTTUVHREFXZ0JUVmMwWC8KMDZOSDE1TW9TNUd1TzVDN3FJQUZjREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFDdkhiUlJxK2VFY2dVb0s5MFFqbkkzejA3enVJLy9yT3NCQVBQL1UwcUFZRjQzaEhoRDdLUU9uazd0Cmw3VFJsOHNDMkhlQ3hEdGloSWVaTWtnNDRoTlBaa09UZEZ2TjJPK29sRytwMFhwWjIrenFwV1pmaXl1bm5FeXUKOWgwUnpzTldEYmpQd2g5dHZTWjhjcGtrTnJVZER6T0dFSHhweElzZ2hiczhXWkZaRGFCOFo3Qi9NSEpaQ1FkZQp3Qzk1VDA5T3U4NWtlbHFXVzIyTlVpQjdsbCsvTmJWRGM1OTkrWjEvaFo4dlpac0xiN0hOdldrK3JUVWNLbEw2ClQxMjFoWmV5cjVpU1dsQmRObUYyUnZPb2dPR21VSlR1WjEzbEJtTHZYUWdHdVc3VEgrNWNnY3N0ckxDL2JtcDgKZWhQUUo1akdROVcvTmpQRzA4MjBkb1dwMEZIRgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        namespace: opa
        name: validate
---
kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: mutating-webhook
webhooks:
  - name: http.mutating.webhook
    namespaceSelector:
      matchLabels:
        mutate: "true"
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["network.as.a.service"]
        apiVersions: ["*"]
        resources: ["interfaces"]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZtZ0F3SUJBZ0lVTWRxNTlQWkM5RjNmTThPWkRKQURTa2xNenBRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01ZV1J0YVhOemFXOXVYMk5oTUNBWERURTVNVEF3TVRFMU1USTFORm9ZRHpJeQpPVE13TnpFMk1UVXhNalUwV2pBWE1SVXdFd1lEVlFRRERBeGhaRzFwYzNOcGIyNWZZMkV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURPQUFNM0RmdFBVMDU1U09kOHViZ2ZxKzg3VTFyMC9EdEgKOHVuS1p0L1BrK1BwZ2s3Z09lczBxNElBbVNsemFFNWN5bXhFYlo3SW92ZzU0QWtQWFBFVENDek5ITFRINUJHRwpJTEViOS9YYlZLUm56Wk40Zk9PekNnZEpVcEdhTjBlcWNFdTIxby9nVkl3TmdRMWRBa0ZzdmpFTkZnd0o5M1FQClQ4N0pqeE14VCtYNGVpYmx6emdUeU9oWnVmTEV6a1dKVis0RngyZFFvZzdFTGlINlN0YlZVOSt1TUFPRHZrRTAKd0dUUUZ6cm9Iem96aXhScVoyWDZ1TENrc2lTNG1tZlhKQUZqSmRYZHQ1ekZKZzVlZzlLdm1weEErU0RwbTI3TApySUtoTUQwazJJRmFuYjQzeXpDcVV3anhjOTZBT01jSDByNzhLQkN1dXpMVjBLbWJJeUZ0QWdNQkFBR2pVekJSCk1CMEdBMVVkRGdRV0JCVFZjMFgvMDZOSDE1TW9TNUd1TzVDN3FJQUZjREFmQmdOVkhTTUVHREFXZ0JUVmMwWC8KMDZOSDE1TW9TNUd1TzVDN3FJQUZjREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFDdkhiUlJxK2VFY2dVb0s5MFFqbkkzejA3enVJLy9yT3NCQVBQL1UwcUFZRjQzaEhoRDdLUU9uazd0Cmw3VFJsOHNDMkhlQ3hEdGloSWVaTWtnNDRoTlBaa09UZEZ2TjJPK29sRytwMFhwWjIrenFwV1pmaXl1bm5FeXUKOWgwUnpzTldEYmpQd2g5dHZTWjhjcGtrTnJVZER6T0dFSHhweElzZ2hiczhXWkZaRGFCOFo3Qi9NSEpaQ1FkZQp3Qzk1VDA5T3U4NWtlbHFXVzIyTlVpQjdsbCsvTmJWRGM1OTkrWjEvaFo4dlpac0xiN0hOdldrK3JUVWNLbEw2ClQxMjFoWmV5cjVpU1dsQmRObUYyUnZPb2dPR21VSlR1WjEzbEJtTHZYUWdHdVc3VEgrNWNnY3N0ckxDL2JtcDgKZWhQUUo1akdROVcvTmpQRzA4MjBkb1dwMEZIRgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        namespace: mutate
        name: mutate
